# Generated by Django 4.2.1 on 2023-05-31 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TaskForMe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businesshours',
            old_name='dayOfWeek',
            new_name='day',
        ),
    ]
