# Generated by Django 4.2.1 on 2023-06-02 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskForMe', '0002_rename_dayofweek_businesshours_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=100)),
            ],
        ),
    ]
